use crate::EventEnvelope;

/// Core identity and hydration trait for an aggregate.
///
/// State is reconstructed by replaying stored events through version-matched
/// `#[event_combiner]` impls. The `#[aggregate]` macro generates the `hydrate`
/// implementation — it reads `event_type` and `event_version` from each
/// `EventEnvelope`, deserializes the payload, and dispatches to the combiner
/// registered at that version. No upcasting or downcasting occurs — each
/// event version is processed at the schema it was stored with.
///
/// Command handling is owned by `#[command_handler]` impls — the aggregate
/// does not define `handle`.
pub trait Aggregate: Sized + Send + Sync + 'static {
    type State: Default + Send + Sync;
    type Error: std::error::Error + Send + Sync + 'static;

    /// Reconstruct aggregate state from stored events.
    /// Generated by the #[aggregate] macro — reads event_type + event_version
    /// from each EventEnvelope and dispatches to version-matched #[event_combiner] impls.
    fn hydrate(
        state: &mut Self::State,
        events: impl Iterator<Item = EventEnvelope>,
    ) -> Result<(), Self::Error> {
        let _ = (state, events);
        Ok(())
    }
}
