use crate::EventEnvelope;
use std::any::Any;

/// Core identity and hydration trait for an aggregate.
///
/// `upcast` transforms raw stored `EventEnvelope`s into typed domain events
/// during hydration. `hydrate` applies those events to state via the dispatch
/// table generated by `#[aggregate]` and `#[event_combiner]` macros.
///
/// State folding logic is owned by individual `#[event_combiner]` impls —
/// the aggregate itself does not define `apply`. Command handling is owned
/// by `#[command_handler]` impls — the aggregate does not define `handle`.
pub trait Aggregate: Sized + Send + Sync + 'static {
    type State: Default + Send + Sync;
    type Error: std::error::Error + Send + Sync + 'static;

    /// Transform a raw stored EventEnvelope into a typed domain event.
    /// Called during hydration. Handles schema migrations via event_version.
    fn upcast(raw: EventEnvelope) -> Result<Box<dyn Any>, Self::Error>;

    /// Reconstruct aggregate state from a sequence of upcasted events.
    /// Generated by the #[aggregate] macro — dispatches to registered #[event_combiner] impls.
    fn hydrate(state: &mut Self::State, events: impl Iterator<Item = Box<dyn Any>>) {
        let _ = (state, events);
    }
}
