use super::aggregate::Aggregate;
use async_trait::async_trait;

/// Validates a command against current aggregate state and produces a single event.
/// One CommandHandler per command type per version. Generated by the #[command_handler] macro.
/// A command produces exactly one event or returns `Err`. Rejection is `Err`, not a separate event type.
#[async_trait]
pub trait CommandHandler<A: Aggregate>: Send + Sync + 'static {
    type Command: Send + Sync;
    type Event: Send + Sync;
    type Error: std::error::Error + Send + Sync + 'static;

    async fn handle(
        &self,
        state: &A::State,
        command: Self::Command,
    ) -> Result<Self::Event, Self::Error>;
}
