use async_trait::async_trait;
use super::aggregate::Aggregate;

/// Validates a command against current aggregate state and produces events.
/// One CommandHandler per command type. Generated by the #[command_handler] macro.
#[async_trait]
pub trait CommandHandler<A: Aggregate>: Send + Sync + 'static {
    type Command: Send + Sync;
    type Event: Send + Sync;
    type Error: std::error::Error + Send + Sync + 'static;

    async fn handle(
        &self,
        state: &A::State,
        command: Self::Command,
    ) -> Result<Vec<Self::Event>, Self::Error>;
}
