/// Synchronous, pure state folding for a single event version.
/// Generated by the `#[event_combiner]` macro — users never implement this directly.
pub trait EventCombiner<A>: Send + Sync + 'static {
    fn combine(&self, state: &mut A);
}
