/// Applies a single event type to a projection's read model.
/// Generated by the `#[projection_handler]` macro — users never implement this directly.
pub trait ProjectionHandler<P>: Send + Sync + 'static {
    type Event: Send + Sync;
    fn apply(&self, event: &Self::Event, store: &mut P);
}
