[package]
name = "gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
canon-core                    = { path = "../../canon-core" }
canon-demo-shared             = { path = "../shared", features = ["db"] }
canon-event-store             = { path = "../../canon-event-store" }
canon-event-store-cassandra   = { path = "../../canon-event-store-cassandra" }
canon-snapshot-store          = { path = "../../canon-snapshot-store" }
canon-snapshot-store-yugabyte = { path = "../../canon-snapshot-store-yugabyte" }
canon-command-store-yugabyte   = { path = "../../canon-command-store-yugabyte" }
canon-deadletter              = { path = "../../canon-deadletter" }

fleet-service                 = { path = "../fleet-service" }
cargo-service                 = { path = "../cargo-service" }
navigation-service            = { path = "../navigation-service" }
supply-service                = { path = "../supply-service" }
station-service               = { path = "../station-service" }

axum        = { version = "0.7", features = ["ws"] }
tokio       = { workspace = true }
tower-http  = { version = "0.5", features = ["cors"] }
thiserror   = { workspace = true }
serde       = { workspace = true }
serde_json  = { workspace = true }
uuid        = { workspace = true }
bytes       = { workspace = true }
chrono      = { workspace = true }
tracing     = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
futures     = { workspace = true }
rdkafka     = { workspace = true }
sqlx        = { version = "0.8", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json", "derive"] }
