//! Route aggregate — the core domain entity for the navigation service.
//!
//! State is reconstructed by replaying events through version-matched
//! event combiners generated by `#[event_combiner]` macros.

/// Route aggregate state. Tracks ship assignment, waypoints, position, and
/// arrival status.
///
/// Snapshot cadence: every 50 events.
#[canon_core::aggregate(snapshot_every = 50)]
pub struct Route {
    pub ship_id: Option<uuid::Uuid>,
    pub waypoints: Vec<uuid::Uuid>,
    pub current_waypoint_index: usize,
    pub arrived: bool,
}

#[cfg(test)]
mod tests {
    use super::*;
    use bytes::Bytes;
    use canon_core::{Aggregate, AggregateId, EventEnvelope, Version};
    use chrono::Utc;
    use uuid::Uuid;

    use crate::events::{PositionUpdated, RoutePlanned, ShipArrivedAtStation};

    fn make_envelope(
        agg_id: &AggregateId,
        version: Version,
        event_type: &str,
        payload: Vec<u8>,
        correlation_id: Uuid,
    ) -> EventEnvelope {
        EventEnvelope {
            event_id: Uuid::new_v4(),
            aggregate_id: agg_id.clone(),
            version,
            event_type: event_type.to_string(),
            event_version: 1,
            payload: Bytes::from(payload),
            correlation_id,
            causation_id: Uuid::new_v4(),
            timestamp: Utc::now(),
        }
    }

    #[test]
    fn route_default_state() {
        let route = Route::default();
        assert!(route.ship_id.is_none());
        assert!(route.waypoints.is_empty());
        assert_eq!(route.current_waypoint_index, 0);
        assert!(!route.arrived);
    }

    #[test]
    fn route_serde_roundtrip() {
        let route = Route {
            ship_id: Some(Uuid::new_v4()),
            waypoints: vec![Uuid::new_v4()],
            current_waypoint_index: 0,
            arrived: false,
        };
        let json = serde_json::to_vec(&route).expect("serialize");
        let back: Route = serde_json::from_slice(&json).expect("deserialize");
        assert_eq!(back.ship_id, route.ship_id);
        assert_eq!(back.waypoints, route.waypoints);
    }

    #[test]
    fn hydrate_route_planned() {
        let mut route = Route::default();
        let agg_id = AggregateId::new();
        let ship_id = Uuid::new_v4();
        let wp1 = Uuid::new_v4();
        let wp2 = Uuid::new_v4();
        let corr = Uuid::new_v4();

        let planned = RoutePlanned {
            route_id: *agg_id.as_uuid(),
            ship_id,
            waypoints: vec![wp1, wp2],
        };
        let payload = serde_json::to_vec(&planned).expect("serialize");
        let envelope = make_envelope(&agg_id, Version::initial(), "RoutePlanned", payload, corr);

        Route::hydrate(&mut route, std::iter::once(envelope)).expect("hydrate");

        assert_eq!(route.ship_id, Some(ship_id));
        assert_eq!(route.waypoints.len(), 2);
        assert_eq!(route.current_waypoint_index, 0);
        assert!(!route.arrived);
    }

    #[test]
    fn hydrate_full_lifecycle() {
        let mut route = Route::default();
        let agg_id = AggregateId::new();
        let ship_id = Uuid::new_v4();
        let station_id = Uuid::new_v4();
        let wp1 = Uuid::new_v4();
        let wp2 = station_id;
        let corr = Uuid::new_v4();

        let planned = RoutePlanned {
            route_id: *agg_id.as_uuid(),
            ship_id,
            waypoints: vec![wp1, wp2],
        };
        let position = PositionUpdated {
            route_id: *agg_id.as_uuid(),
            ship_id,
            waypoint_id: wp2,
        };
        let arrived = ShipArrivedAtStation {
            route_id: *agg_id.as_uuid(),
            ship_id,
            station_id,
        };

        let events = vec![
            make_envelope(
                &agg_id,
                Version::initial(),
                "RoutePlanned",
                serde_json::to_vec(&planned).expect("serialize"),
                corr,
            ),
            make_envelope(
                &agg_id,
                Version::from_u64(1),
                "PositionUpdated",
                serde_json::to_vec(&position).expect("serialize"),
                corr,
            ),
            make_envelope(
                &agg_id,
                Version::from_u64(2),
                "ShipArrivedAtStation",
                serde_json::to_vec(&arrived).expect("serialize"),
                corr,
            ),
        ];

        Route::hydrate(&mut route, events.into_iter()).expect("hydrate");

        assert_eq!(route.ship_id, Some(ship_id));
        assert_eq!(route.current_waypoint_index, 1);
        assert!(route.arrived);
    }

    #[test]
    fn hydrate_unknown_event_returns_error() {
        let mut route = Route::default();
        let agg_id = AggregateId::new();
        let events = vec![make_envelope(
            &agg_id,
            Version::initial(),
            "UnknownEvent",
            b"{}".to_vec(),
            Uuid::new_v4(),
        )];

        let result = Route::hydrate(&mut route, events.into_iter());
        assert!(result.is_err());
    }
}
