apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canon-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "canon-prod-ip"
    networking.gke.io/managed-certificates: "canon-prod-cert"
    networking.gke.io/v1beta1.FrontendConfig: "canon-frontend-config"
spec:
  defaultBackend:
    service:
      name: frontend
      port:
        number: 80
  rules:
    - host: canon.mopjones.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
