FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*
ARG BINARY_NAME
COPY target/aarch64-unknown-linux-gnu/release/${BINARY_NAME} /usr/local/bin/service
RUN chmod +x /usr/local/bin/service
CMD ["/usr/local/bin/service"]
