use crate::aggregate::{CargoItem, ManifestState, ManifestStatus};
use crate::events::{
    CargoLoaded, CargoLoadedV2HasCombiner, CargoUnloaded, CargoUnloadedV1HasCombiner,
    ManifestClosed, ManifestClosedV1HasCombiner, ManifestCreated, ManifestCreatedV1HasCombiner,
    UnloadingStarted, UnloadingStartedV1HasCombiner,
};

// ---------------------------------------------------------------------------
// Event combiners — using #[event_combiner] macros for standard events
// ---------------------------------------------------------------------------

#[canon_core::event_combiner(ManifestState, version = 1)]
impl ManifestCreated {
    fn combine(&self, state: &mut ManifestState) {
        state.ship_id = Some(self.ship_id);
        state.voyage_id = Some(self.voyage_id);
        state.status = ManifestStatus::Open;
    }
}

/// CargoLoaded v2 combiner (current schema version).
/// v1 events are upcast to v2 before reaching the combiner (see `upcast` module).
#[canon_core::event_combiner(ManifestState, version = 2)]
impl CargoLoaded {
    fn combine(&self, state: &mut ManifestState) {
        state.items.push(CargoItem {
            item_id: self.item_id,
            weight_kg: self.weight_kg.max(0.0).round() as u32,
            unloaded: false,
        });
    }
}

/// v1 combiner for CargoLoaded — deserializes the v1 payload (which lacks the
/// `description` and `manifest_id` fields) and applies it via the v2 combiner.
/// The combiner only uses `item_id` and `weight_kg` for state folding, so the
/// missing `manifest_id` (set to nil) and `description` (set to migration marker)
/// have no effect on aggregate state.
#[allow(non_snake_case)]
fn __canon_apply_cargoloaded_v1(
    payload: &[u8],
    state: &mut dyn std::any::Any,
) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    #[derive(serde::Deserialize)]
    struct CargoLoadedV1 {
        item_id: uuid::Uuid,
        weight_kg: f32,
    }
    let v1: CargoLoadedV1 = canon_core::__deserialize(payload)?;
    let v2 = CargoLoaded {
        manifest_id: uuid::Uuid::nil(),
        item_id: v1.item_id,
        weight_kg: v1.weight_kg,
        description: "(migrated from v1)".to_string(),
    };
    let state = state.downcast_mut::<ManifestState>().ok_or_else(
        || -> Box<dyn std::error::Error + Send + Sync> {
            "aggregate state type mismatch in event combiner".into()
        },
    )?;
    // Call the v2 combiner's standalone function generated by #[event_combiner]
    __canon_combine_cargoloaded_v2(&v2, state);
    Ok(())
}

canon_core::__submit! {
    canon_core::EventCombinerRegistration {
        aggregate_type_id: std::any::TypeId::of::<ManifestState>(),
        event_type_name: "CargoLoaded",
        event_version: 1,
        apply_fn: __canon_apply_cargoloaded_v1,
    }
}

#[canon_core::event_combiner(ManifestState, version = 1)]
impl UnloadingStarted {
    fn combine(&self, state: &mut ManifestState) {
        state.status = ManifestStatus::Unloading;
    }
}

#[canon_core::event_combiner(ManifestState, version = 1)]
impl CargoUnloaded {
    fn combine(&self, state: &mut ManifestState) {
        for item in &mut state.items {
            if item.item_id == self.item_id {
                item.unloaded = true;
            }
        }
    }
}

#[canon_core::event_combiner(ManifestState, version = 1)]
impl ManifestClosed {
    fn combine(&self, state: &mut ManifestState) {
        state.status = ManifestStatus::Closed;
    }
}
