[package]
name = "canon-outbound-queue-kafka"
version = "0.1.0"
edition = "2021"

[dependencies]
canon-core = { path = "../canon-core" }
canon-outbound-queue = { path = "../canon-outbound-queue" }
async-trait = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
rdkafka = { version = "0.36" }

[dev-dependencies]
tokio = { workspace = true, features = ["full", "test-util"] }
