[package]
name = "canon-event-store-cassandra"
version = "0.1.0"
edition = "2021"

[dependencies]
canon-core = { path = "../canon-core" }
canon-event-store = { path = "../canon-event-store" }
async-trait = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
bytes = { workspace = true }
scylla = "0.15"

[dev-dependencies]
tokio = { workspace = true }
