use uuid::Uuid;

use crate::aggregate::Station;
use crate::error::StationError;
use crate::events::{
    CapacityUpdated, CargoReceived, ShipDocked, StationOffline, StationRegistered, StationStockLow,
    StockDrained,
};

// Re-export shared command types.
pub use canon_demo_shared::commands::{
    DrainStock, RecordCargoReceived, RecordDocking, RegisterStation, UpdateCapacity,
};

// Import marker traits generated by #[command] in the shared crate.
// The #[command_handler] macro needs these in scope to satisfy compile-time enforcement.
use canon_demo_shared::commands::{
    DrainStockV1HasHandler, RecordCargoReceivedV1HasHandler, RecordDockingV1HasHandler,
    RegisterStationV1HasHandler, UpdateCapacityV1HasHandler,
};

/// Internal command: checks stock level after cargo is consumed/drained.
/// If stock falls below 20% of capacity, produces `StationStockLow`.
/// If stock is within normal range, returns an error (command rejected — no event emitted).
#[canon_core::command(Station, version = 1, produces = [StationStockLow])]
pub struct CheckStockLevel {
    pub station_id: Uuid,
}

/// Internal command: checks if stock has reached zero (game-over condition).
/// Produces `StationOffline` if current_stock_kg == 0.
#[canon_core::command(Station, version = 1, produces = [StationOffline])]
pub struct CheckStationOffline {
    pub station_id: Uuid,
}

// ---------------------------------------------------------------------------
// Command handlers
// ---------------------------------------------------------------------------

#[canon_core::command_handler(Station, version = 1)]
impl RegisterStationHandler {
    type Error = StationError;

    fn handle(
        &self,
        state: &Station,
        cmd: RegisterStation,
    ) -> Result<StationRegistered, StationError> {
        if state.registered {
            return Err(StationError::AlreadyRegistered);
        }
        if cmd.name.is_empty() {
            return Err(StationError::EmptyName);
        }
        if cmd.capacity_kg <= 0.0 {
            return Err(StationError::InvalidCapacity);
        }
        Ok(StationRegistered {
            station_id: Uuid::new_v4(),
            name: cmd.name,
            capacity_kg: cmd.capacity_kg,
        })
    }
}

#[canon_core::command_handler(Station, version = 1)]
impl RecordDockingHandler {
    type Error = StationError;

    fn handle(&self, state: &Station, cmd: RecordDocking) -> Result<ShipDocked, StationError> {
        if !state.registered {
            return Err(StationError::NotRegistered);
        }
        if state.offline {
            return Err(StationError::StationOffline);
        }
        if state.docked_ships.contains(&cmd.ship_id) {
            return Err(StationError::ShipAlreadyDocked {
                ship_id: cmd.ship_id,
            });
        }
        Ok(ShipDocked {
            station_id: cmd.station_id,
            ship_id: cmd.ship_id,
        })
    }
}

#[canon_core::command_handler(Station, version = 1)]
impl RecordCargoReceivedHandler {
    type Error = StationError;

    fn handle(
        &self,
        state: &Station,
        cmd: RecordCargoReceived,
    ) -> Result<CargoReceived, StationError> {
        if !state.registered {
            return Err(StationError::NotRegistered);
        }
        if state.offline {
            return Err(StationError::StationOffline);
        }
        if cmd.weight_kg <= 0.0 {
            return Err(StationError::InvalidWeight);
        }
        Ok(CargoReceived {
            station_id: cmd.station_id,
            manifest_id: cmd.manifest_id,
            weight_kg: cmd.weight_kg,
        })
    }
}

#[canon_core::command_handler(Station, version = 1)]
impl UpdateCapacityHandler {
    type Error = StationError;

    fn handle(
        &self,
        state: &Station,
        cmd: UpdateCapacity,
    ) -> Result<CapacityUpdated, StationError> {
        if !state.registered {
            return Err(StationError::NotRegistered);
        }
        if cmd.capacity_kg <= 0.0 {
            return Err(StationError::InvalidCapacity);
        }
        Ok(CapacityUpdated {
            station_id: cmd.station_id,
            capacity_kg: cmd.capacity_kg,
        })
    }
}

#[canon_core::command_handler(Station, version = 1)]
impl DrainStockHandler {
    type Error = StationError;

    fn handle(&self, state: &Station, cmd: DrainStock) -> Result<StockDrained, StationError> {
        if !state.registered {
            return Err(StationError::NotRegistered);
        }
        if state.offline {
            return Err(StationError::StationOffline);
        }
        if state.current_stock_kg <= 0.0 {
            return Err(StationError::StockDepleted);
        }
        let drain = cmd.drain_kg.min(state.current_stock_kg);
        Ok(StockDrained {
            station_id: cmd.station_id,
            drain_kg: drain,
            remaining_kg: state.current_stock_kg - drain,
        })
    }
}

/// Threshold fraction: stock level below 20% of capacity triggers StationStockLow.
const STOCK_LOW_THRESHOLD: f32 = 0.2;

#[canon_core::command_handler(Station, version = 1)]
impl CheckStockLevelHandler {
    type Error = StationError;

    fn handle(
        &self,
        state: &Station,
        cmd: CheckStockLevel,
    ) -> Result<StationStockLow, StationError> {
        if !state.registered {
            return Err(StationError::NotRegistered);
        }
        let threshold_kg = state.capacity_kg * STOCK_LOW_THRESHOLD;
        if state.current_stock_kg < threshold_kg {
            Ok(StationStockLow {
                station_id: cmd.station_id,
                current_stock_kg: state.current_stock_kg,
                threshold_kg,
            })
        } else {
            // Stock is within normal range — no event needed.
            // Rejection via Err is the canonical way to produce no event.
            Err(StationError::StockLevelNormal)
        }
    }
}

#[canon_core::command_handler(Station, version = 1)]
impl CheckStationOfflineHandler {
    type Error = StationError;

    fn handle(
        &self,
        state: &Station,
        cmd: CheckStationOffline,
    ) -> Result<StationOffline, StationError> {
        if !state.registered {
            return Err(StationError::NotRegistered);
        }
        if state.offline {
            return Err(StationError::AlreadyOffline);
        }
        if state.current_stock_kg <= 0.0 {
            Ok(StationOffline {
                station_id: cmd.station_id,
            })
        } else {
            Err(StationError::StockLevelNormal)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use canon_core::CommandHandler;

    fn registered_station() -> Station {
        Station {
            name: "Alpha Station".to_string(),
            capacity_kg: 1000.0,
            current_stock_kg: 500.0,
            drain_rate_kg_per_s: 1.0,
            supplied_by: None,
            docked_ships: Vec::new(),
            registered: true,
            offline: false,
        }
    }

    // -- RegisterStation tests --

    #[tokio::test]
    async fn register_station_succeeds() {
        let handler = RegisterStationHandler;
        let state = Station::default();
        let cmd = RegisterStation {
            name: "Alpha Station".to_string(),
            capacity_kg: 1000.0,
        };
        let result = handler.handle(&state, cmd).await;
        assert!(result.is_ok());
        let event = result.unwrap();
        assert_eq!(event.name, "Alpha Station");
        assert!((event.capacity_kg - 1000.0).abs() < f32::EPSILON);
    }

    #[tokio::test]
    async fn register_station_rejects_empty_name() {
        let handler = RegisterStationHandler;
        let state = Station::default();
        let cmd = RegisterStation {
            name: String::new(),
            capacity_kg: 1000.0,
        };
        let result = handler.handle(&state, cmd).await;
        assert!(matches!(result, Err(StationError::EmptyName)));
    }

    #[tokio::test]
    async fn register_station_rejects_zero_capacity() {
        let handler = RegisterStationHandler;
        let state = Station::default();
        let cmd = RegisterStation {
            name: "Test".to_string(),
            capacity_kg: 0.0,
        };
        let result = handler.handle(&state, cmd).await;
        assert!(matches!(result, Err(StationError::InvalidCapacity)));
    }

    #[tokio::test]
    async fn register_station_rejects_already_registered() {
        let handler = RegisterStationHandler;
        let state = registered_station();
        let cmd = RegisterStation {
            name: "Test".to_string(),
            capacity_kg: 1000.0,
        };
        let result = handler.handle(&state, cmd).await;
        assert!(matches!(result, Err(StationError::AlreadyRegistered)));
    }

    // -- RecordDocking tests --

    #[tokio::test]
    async fn record_docking_succeeds() {
        let handler = RecordDockingHandler;
        let state = registered_station();
        let ship_id = Uuid::new_v4();
        let station_id = Uuid::new_v4();
        let cmd = RecordDocking {
            station_id,
            ship_id,
        };
        let result = handler.handle(&state, cmd).await;
        assert!(result.is_ok());
        let event = result.unwrap();
        assert_eq!(event.ship_id, ship_id);
        assert_eq!(event.station_id, station_id);
    }

    #[tokio::test]
    async fn record_docking_rejects_not_registered() {
        let handler = RecordDockingHandler;
        let state = Station::default();
        let cmd = RecordDocking {
            station_id: Uuid::new_v4(),
            ship_id: Uuid::new_v4(),
        };
        let result = handler.handle(&state, cmd).await;
        assert!(matches!(result, Err(StationError::NotRegistered)));
    }

    #[tokio::test]
    async fn record_docking_rejects_already_docked() {
        let handler = RecordDockingHandler;
        let ship_id = Uuid::new_v4();
        let mut state = registered_station();
        state.docked_ships.push(ship_id);
        let cmd = RecordDocking {
            station_id: Uuid::new_v4(),
            ship_id,
        };
        let result = handler.handle(&state, cmd).await;
        assert!(matches!(
            result,
            Err(StationError::ShipAlreadyDocked { .. })
        ));
    }

    #[tokio::test]
    async fn record_docking_rejects_when_offline() {
        let handler = RecordDockingHandler;
        let mut state = registered_station();
        state.offline = true;
        let cmd = RecordDocking {
            station_id: Uuid::new_v4(),
            ship_id: Uuid::new_v4(),
        };
        let result = handler.handle(&state, cmd).await;
        assert!(matches!(result, Err(StationError::StationOffline)));
    }

    // -- RecordCargoReceived tests --

    #[tokio::test]
    async fn record_cargo_received_succeeds() {
        let handler = RecordCargoReceivedHandler;
        let state = registered_station();
        let station_id = Uuid::new_v4();
        let manifest_id = Uuid::new_v4();
        let cmd = RecordCargoReceived {
            station_id,
            manifest_id,
            weight_kg: 50.0,
        };
        let result = handler.handle(&state, cmd).await;
        assert!(result.is_ok());
        let event = result.unwrap();
        assert_eq!(event.station_id, station_id);
        assert!((event.weight_kg - 50.0).abs() < f32::EPSILON);
    }

    #[tokio::test]
    async fn record_cargo_received_rejects_not_registered() {
        let handler = RecordCargoReceivedHandler;
        let state = Station::default();
        let cmd = RecordCargoReceived {
            station_id: Uuid::new_v4(),
            manifest_id: Uuid::new_v4(),
            weight_kg: 50.0,
        };
        let result = handler.handle(&state, cmd).await;
        assert!(matches!(result, Err(StationError::NotRegistered)));
    }

    #[tokio::test]
    async fn record_cargo_received_rejects_zero_weight() {
        let handler = RecordCargoReceivedHandler;
        let state = registered_station();
        let cmd = RecordCargoReceived {
            station_id: Uuid::new_v4(),
            manifest_id: Uuid::new_v4(),
            weight_kg: 0.0,
        };
        let result = handler.handle(&state, cmd).await;
        assert!(matches!(result, Err(StationError::InvalidWeight)));
    }

    #[tokio::test]
    async fn record_cargo_received_rejects_when_offline() {
        let handler = RecordCargoReceivedHandler;
        let mut state = registered_station();
        state.offline = true;
        let cmd = RecordCargoReceived {
            station_id: Uuid::new_v4(),
            manifest_id: Uuid::new_v4(),
            weight_kg: 50.0,
        };
        let result = handler.handle(&state, cmd).await;
        assert!(matches!(result, Err(StationError::StationOffline)));
    }

    // -- UpdateCapacity tests --

    #[tokio::test]
    async fn update_capacity_succeeds() {
        let handler = UpdateCapacityHandler;
        let state = registered_station();
        let station_id = Uuid::new_v4();
        let cmd = UpdateCapacity {
            station_id,
            capacity_kg: 2000.0,
        };
        let result = handler.handle(&state, cmd).await;
        assert!(result.is_ok());
        let event = result.unwrap();
        assert!((event.capacity_kg - 2000.0).abs() < f32::EPSILON);
    }

    #[tokio::test]
    async fn update_capacity_rejects_not_registered() {
        let handler = UpdateCapacityHandler;
        let state = Station::default();
        let cmd = UpdateCapacity {
            station_id: Uuid::new_v4(),
            capacity_kg: 2000.0,
        };
        let result = handler.handle(&state, cmd).await;
        assert!(matches!(result, Err(StationError::NotRegistered)));
    }

    #[tokio::test]
    async fn update_capacity_rejects_zero() {
        let handler = UpdateCapacityHandler;
        let state = registered_station();
        let cmd = UpdateCapacity {
            station_id: Uuid::new_v4(),
            capacity_kg: 0.0,
        };
        let result = handler.handle(&state, cmd).await;
        assert!(matches!(result, Err(StationError::InvalidCapacity)));
    }

    // -- CheckStockLevel / threshold tests --

    #[tokio::test]
    async fn check_stock_level_emits_when_below_threshold() {
        let handler = CheckStockLevelHandler;
        let mut state = registered_station();
        // capacity = 1000, threshold = 200 (20%). stock = 150 < 200 -> StationStockLow
        state.current_stock_kg = 150.0;
        let station_id = Uuid::new_v4();
        let cmd = CheckStockLevel { station_id };
        let result = handler.handle(&state, cmd).await;
        assert!(result.is_ok());
        let event = result.unwrap();
        assert!((event.current_stock_kg - 150.0).abs() < f32::EPSILON);
        assert!((event.threshold_kg - 200.0).abs() < f32::EPSILON);
    }

    #[tokio::test]
    async fn check_stock_level_rejects_when_above_threshold() {
        let handler = CheckStockLevelHandler;
        let mut state = registered_station();
        // capacity = 1000, threshold = 200 (20%). stock = 500 >= 200 -> no event
        state.current_stock_kg = 500.0;
        let station_id = Uuid::new_v4();
        let cmd = CheckStockLevel { station_id };
        let result = handler.handle(&state, cmd).await;
        assert!(matches!(result, Err(StationError::StockLevelNormal)));
    }

    #[tokio::test]
    async fn check_stock_level_rejects_at_exact_threshold() {
        let handler = CheckStockLevelHandler;
        let mut state = registered_station();
        // capacity = 1000, threshold = 200 (20%). stock = 200 is NOT < 200 -> no event
        state.current_stock_kg = 200.0;
        let station_id = Uuid::new_v4();
        let cmd = CheckStockLevel { station_id };
        let result = handler.handle(&state, cmd).await;
        assert!(matches!(result, Err(StationError::StockLevelNormal)));
    }

    // -- CheckStationOffline tests --

    #[tokio::test]
    async fn check_station_offline_emits_at_zero_stock() {
        let handler = CheckStationOfflineHandler;
        let mut state = registered_station();
        state.current_stock_kg = 0.0;
        let station_id = Uuid::new_v4();
        let cmd = CheckStationOffline { station_id };
        let result = handler.handle(&state, cmd).await;
        assert!(result.is_ok());
        let event = result.unwrap();
        assert_eq!(event.station_id, station_id);
    }

    #[tokio::test]
    async fn check_station_offline_rejects_with_stock() {
        let handler = CheckStationOfflineHandler;
        let state = registered_station();
        let station_id = Uuid::new_v4();
        let cmd = CheckStationOffline { station_id };
        let result = handler.handle(&state, cmd).await;
        assert!(matches!(result, Err(StationError::StockLevelNormal)));
    }

    #[tokio::test]
    async fn check_station_offline_rejects_already_offline() {
        let handler = CheckStationOfflineHandler;
        let mut state = registered_station();
        state.current_stock_kg = 0.0;
        state.offline = true;
        let station_id = Uuid::new_v4();
        let cmd = CheckStationOffline { station_id };
        let result = handler.handle(&state, cmd).await;
        assert!(matches!(result, Err(StationError::AlreadyOffline)));
    }

    // -- DrainStock tests --

    #[tokio::test]
    async fn drain_stock_succeeds() {
        let handler = DrainStockHandler;
        let state = registered_station();
        let station_id = Uuid::new_v4();
        let cmd = DrainStock {
            station_id,
            drain_kg: 100.0,
        };
        let result = handler.handle(&state, cmd).await;
        assert!(result.is_ok());
        let event = result.unwrap();
        assert!((event.drain_kg - 100.0).abs() < f32::EPSILON);
        assert!((event.remaining_kg - 400.0).abs() < f32::EPSILON);
    }

    #[tokio::test]
    async fn drain_stock_clamps_to_available() {
        let handler = DrainStockHandler;
        let mut state = registered_station();
        state.current_stock_kg = 50.0;
        let station_id = Uuid::new_v4();
        let cmd = DrainStock {
            station_id,
            drain_kg: 100.0,
        };
        let result = handler.handle(&state, cmd).await;
        assert!(result.is_ok());
        let event = result.unwrap();
        assert!((event.drain_kg - 50.0).abs() < f32::EPSILON);
        assert!((event.remaining_kg - 0.0).abs() < f32::EPSILON);
    }

    #[tokio::test]
    async fn drain_stock_rejects_not_registered() {
        let handler = DrainStockHandler;
        let state = Station::default();
        let cmd = DrainStock {
            station_id: Uuid::new_v4(),
            drain_kg: 10.0,
        };
        let result = handler.handle(&state, cmd).await;
        assert!(matches!(result, Err(StationError::NotRegistered)));
    }

    #[tokio::test]
    async fn drain_stock_rejects_when_offline() {
        let handler = DrainStockHandler;
        let mut state = registered_station();
        state.offline = true;
        let cmd = DrainStock {
            station_id: Uuid::new_v4(),
            drain_kg: 10.0,
        };
        let result = handler.handle(&state, cmd).await;
        assert!(matches!(result, Err(StationError::StationOffline)));
    }

    #[tokio::test]
    async fn drain_stock_rejects_when_depleted() {
        let handler = DrainStockHandler;
        let mut state = registered_station();
        state.current_stock_kg = 0.0;
        let cmd = DrainStock {
            station_id: Uuid::new_v4(),
            drain_kg: 10.0,
        };
        let result = handler.handle(&state, cmd).await;
        assert!(matches!(result, Err(StationError::StockDepleted)));
    }
}
