use uuid::Uuid;

use crate::aggregate::Station;
use crate::error::StationError;
use crate::events::{
    CapacityUpdated, CargoReceived, ShipDocked, StationRegistered, StationStockLow,
};

// Re-export shared command types.
pub use canon_demo_shared::commands::{
    RecordCargoReceived, RecordDocking, RegisterStation, UpdateCapacity,
};

// Import marker traits generated by #[command] in the shared crate.
// The #[command_handler] macro needs these in scope to satisfy compile-time enforcement.
use canon_demo_shared::commands::{
    RecordCargoReceivedV1HasHandler, RecordDockingV1HasHandler, RegisterStationV1HasHandler,
    UpdateCapacityV1HasHandler,
};

/// Internal command: checks stock level after cargo is received.
/// If stock exceeds 80% of capacity, produces `StationStockLow`.
/// If stock is within normal range, returns an error (command rejected — no event emitted).
#[canon_core::command(Station, version = 1, produces = [StationStockLow])]
pub struct CheckStockLevel {
    pub station_id: Uuid,
}

// ---------------------------------------------------------------------------
// Command handlers
// ---------------------------------------------------------------------------

#[canon_core::command_handler(Station, version = 1)]
impl RegisterStationHandler {
    type Error = StationError;

    fn handle(
        &self,
        state: &Station,
        cmd: RegisterStation,
    ) -> Result<StationRegistered, StationError> {
        if state.registered {
            return Err(StationError::AlreadyRegistered);
        }
        if cmd.name.is_empty() {
            return Err(StationError::EmptyName);
        }
        if cmd.capacity_kg <= 0.0 {
            return Err(StationError::InvalidCapacity);
        }
        Ok(StationRegistered {
            station_id: Uuid::new_v4(),
            name: cmd.name,
            capacity_kg: cmd.capacity_kg,
        })
    }
}

#[canon_core::command_handler(Station, version = 1)]
impl RecordDockingHandler {
    type Error = StationError;

    fn handle(&self, state: &Station, cmd: RecordDocking) -> Result<ShipDocked, StationError> {
        if !state.registered {
            return Err(StationError::NotRegistered);
        }
        if state.docked_ships.contains(&cmd.ship_id) {
            return Err(StationError::ShipAlreadyDocked {
                ship_id: cmd.ship_id,
            });
        }
        Ok(ShipDocked {
            station_id: cmd.station_id,
            ship_id: cmd.ship_id,
        })
    }
}

#[canon_core::command_handler(Station, version = 1)]
impl RecordCargoReceivedHandler {
    type Error = StationError;

    fn handle(
        &self,
        state: &Station,
        cmd: RecordCargoReceived,
    ) -> Result<CargoReceived, StationError> {
        if !state.registered {
            return Err(StationError::NotRegistered);
        }
        if cmd.weight_kg <= 0.0 {
            return Err(StationError::InvalidWeight);
        }
        Ok(CargoReceived {
            station_id: cmd.station_id,
            manifest_id: cmd.manifest_id,
            weight_kg: cmd.weight_kg,
        })
    }
}

#[canon_core::command_handler(Station, version = 1)]
impl UpdateCapacityHandler {
    type Error = StationError;

    fn handle(
        &self,
        state: &Station,
        cmd: UpdateCapacity,
    ) -> Result<CapacityUpdated, StationError> {
        if !state.registered {
            return Err(StationError::NotRegistered);
        }
        if cmd.capacity_kg <= 0.0 {
            return Err(StationError::InvalidCapacity);
        }
        Ok(CapacityUpdated {
            station_id: cmd.station_id,
            capacity_kg: cmd.capacity_kg,
        })
    }
}

/// Threshold fraction: stock level above 80% of capacity triggers StationStockLow.
const STOCK_LOW_THRESHOLD: f32 = 0.8;

#[canon_core::command_handler(Station, version = 1)]
impl CheckStockLevelHandler {
    type Error = StationError;

    fn handle(
        &self,
        state: &Station,
        cmd: CheckStockLevel,
    ) -> Result<StationStockLow, StationError> {
        if !state.registered {
            return Err(StationError::NotRegistered);
        }
        let threshold_kg = state.capacity_kg * STOCK_LOW_THRESHOLD;
        if state.current_stock_kg > threshold_kg {
            Ok(StationStockLow {
                station_id: cmd.station_id,
                current_fuel_kg: state.current_stock_kg,
                threshold_kg,
            })
        } else {
            // Stock is within normal range — no event needed.
            // Rejection via Err is the canonical way to produce no event.
            Err(StationError::StockLevelNormal)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use canon_core::CommandHandler;

    fn registered_station() -> Station {
        Station {
            name: "Alpha Station".to_string(),
            capacity_kg: 1000.0,
            current_stock_kg: 0.0,
            docked_ships: Vec::new(),
            registered: true,
        }
    }

    // -- RegisterStation tests --

    #[tokio::test]
    async fn register_station_succeeds() {
        let handler = RegisterStationHandler;
        let state = Station::default();
        let cmd = RegisterStation {
            name: "Alpha Station".to_string(),
            capacity_kg: 1000.0,
        };
        let result = handler.handle(&state, cmd).await;
        assert!(result.is_ok());
        let event = result.unwrap();
        assert_eq!(event.name, "Alpha Station");
        assert!((event.capacity_kg - 1000.0).abs() < f32::EPSILON);
    }

    #[tokio::test]
    async fn register_station_rejects_empty_name() {
        let handler = RegisterStationHandler;
        let state = Station::default();
        let cmd = RegisterStation {
            name: String::new(),
            capacity_kg: 1000.0,
        };
        let result = handler.handle(&state, cmd).await;
        assert!(matches!(result, Err(StationError::EmptyName)));
    }

    #[tokio::test]
    async fn register_station_rejects_zero_capacity() {
        let handler = RegisterStationHandler;
        let state = Station::default();
        let cmd = RegisterStation {
            name: "Test".to_string(),
            capacity_kg: 0.0,
        };
        let result = handler.handle(&state, cmd).await;
        assert!(matches!(result, Err(StationError::InvalidCapacity)));
    }

    #[tokio::test]
    async fn register_station_rejects_already_registered() {
        let handler = RegisterStationHandler;
        let state = registered_station();
        let cmd = RegisterStation {
            name: "Test".to_string(),
            capacity_kg: 1000.0,
        };
        let result = handler.handle(&state, cmd).await;
        assert!(matches!(result, Err(StationError::AlreadyRegistered)));
    }

    // -- RecordDocking tests --

    #[tokio::test]
    async fn record_docking_succeeds() {
        let handler = RecordDockingHandler;
        let state = registered_station();
        let ship_id = Uuid::new_v4();
        let station_id = Uuid::new_v4();
        let cmd = RecordDocking {
            station_id,
            ship_id,
        };
        let result = handler.handle(&state, cmd).await;
        assert!(result.is_ok());
        let event = result.unwrap();
        assert_eq!(event.ship_id, ship_id);
        assert_eq!(event.station_id, station_id);
    }

    #[tokio::test]
    async fn record_docking_rejects_not_registered() {
        let handler = RecordDockingHandler;
        let state = Station::default();
        let cmd = RecordDocking {
            station_id: Uuid::new_v4(),
            ship_id: Uuid::new_v4(),
        };
        let result = handler.handle(&state, cmd).await;
        assert!(matches!(result, Err(StationError::NotRegistered)));
    }

    #[tokio::test]
    async fn record_docking_rejects_already_docked() {
        let handler = RecordDockingHandler;
        let ship_id = Uuid::new_v4();
        let mut state = registered_station();
        state.docked_ships.push(ship_id);
        let cmd = RecordDocking {
            station_id: Uuid::new_v4(),
            ship_id,
        };
        let result = handler.handle(&state, cmd).await;
        assert!(matches!(
            result,
            Err(StationError::ShipAlreadyDocked { .. })
        ));
    }

    // -- RecordCargoReceived tests --

    #[tokio::test]
    async fn record_cargo_received_succeeds() {
        let handler = RecordCargoReceivedHandler;
        let state = registered_station();
        let station_id = Uuid::new_v4();
        let manifest_id = Uuid::new_v4();
        let cmd = RecordCargoReceived {
            station_id,
            manifest_id,
            weight_kg: 50.0,
        };
        let result = handler.handle(&state, cmd).await;
        assert!(result.is_ok());
        let event = result.unwrap();
        assert_eq!(event.station_id, station_id);
        assert!((event.weight_kg - 50.0).abs() < f32::EPSILON);
    }

    #[tokio::test]
    async fn record_cargo_received_rejects_not_registered() {
        let handler = RecordCargoReceivedHandler;
        let state = Station::default();
        let cmd = RecordCargoReceived {
            station_id: Uuid::new_v4(),
            manifest_id: Uuid::new_v4(),
            weight_kg: 50.0,
        };
        let result = handler.handle(&state, cmd).await;
        assert!(matches!(result, Err(StationError::NotRegistered)));
    }

    #[tokio::test]
    async fn record_cargo_received_rejects_zero_weight() {
        let handler = RecordCargoReceivedHandler;
        let state = registered_station();
        let cmd = RecordCargoReceived {
            station_id: Uuid::new_v4(),
            manifest_id: Uuid::new_v4(),
            weight_kg: 0.0,
        };
        let result = handler.handle(&state, cmd).await;
        assert!(matches!(result, Err(StationError::InvalidWeight)));
    }

    // -- UpdateCapacity tests --

    #[tokio::test]
    async fn update_capacity_succeeds() {
        let handler = UpdateCapacityHandler;
        let state = registered_station();
        let station_id = Uuid::new_v4();
        let cmd = UpdateCapacity {
            station_id,
            capacity_kg: 2000.0,
        };
        let result = handler.handle(&state, cmd).await;
        assert!(result.is_ok());
        let event = result.unwrap();
        assert!((event.capacity_kg - 2000.0).abs() < f32::EPSILON);
    }

    #[tokio::test]
    async fn update_capacity_rejects_not_registered() {
        let handler = UpdateCapacityHandler;
        let state = Station::default();
        let cmd = UpdateCapacity {
            station_id: Uuid::new_v4(),
            capacity_kg: 2000.0,
        };
        let result = handler.handle(&state, cmd).await;
        assert!(matches!(result, Err(StationError::NotRegistered)));
    }

    #[tokio::test]
    async fn update_capacity_rejects_zero() {
        let handler = UpdateCapacityHandler;
        let state = registered_station();
        let cmd = UpdateCapacity {
            station_id: Uuid::new_v4(),
            capacity_kg: 0.0,
        };
        let result = handler.handle(&state, cmd).await;
        assert!(matches!(result, Err(StationError::InvalidCapacity)));
    }

    // -- CheckStockLevel / threshold tests --

    #[tokio::test]
    async fn check_stock_level_emits_when_above_threshold() {
        let handler = CheckStockLevelHandler;
        let mut state = registered_station();
        // capacity = 1000, threshold = 800. stock = 850 > 800 -> StationStockLow
        state.current_stock_kg = 850.0;
        let station_id = Uuid::new_v4();
        let cmd = CheckStockLevel { station_id };
        let result = handler.handle(&state, cmd).await;
        assert!(result.is_ok());
        let event = result.unwrap();
        assert!((event.current_fuel_kg - 850.0).abs() < f32::EPSILON);
        assert!((event.threshold_kg - 800.0).abs() < f32::EPSILON);
    }

    #[tokio::test]
    async fn check_stock_level_rejects_when_below_threshold() {
        let handler = CheckStockLevelHandler;
        let mut state = registered_station();
        // capacity = 1000, threshold = 800. stock = 500 <= 800 -> no event
        state.current_stock_kg = 500.0;
        let station_id = Uuid::new_v4();
        let cmd = CheckStockLevel { station_id };
        let result = handler.handle(&state, cmd).await;
        assert!(matches!(result, Err(StationError::StockLevelNormal)));
    }

    #[tokio::test]
    async fn check_stock_level_rejects_at_exact_threshold() {
        let handler = CheckStockLevelHandler;
        let mut state = registered_station();
        // capacity = 1000, threshold = 800. stock = 800 is NOT > 800 -> no event
        state.current_stock_kg = 800.0;
        let station_id = Uuid::new_v4();
        let cmd = CheckStockLevel { station_id };
        let result = handler.handle(&state, cmd).await;
        assert!(matches!(result, Err(StationError::StockLevelNormal)));
    }
}
