apiVersion: v1
kind: ConfigMap
metadata:
  name: canon-demo-config
  labels:
    app.kubernetes.io/part-of: canon-demo
data:
  kafka_brokers: "kafka:9092"
  cassandra_nodes: "cassandra:9042"
  yugabyte_url: "postgres://canon:canon@yugabytedb:5433/canon"
  gateway_url: "http://gateway:8080"
